name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #   with:
    #     submodules: 'true'
    # - name: Upgrade pip and fix permissions issue
    #   run: pip install --upgrade pip && git config --global --add safe.directory /github/workspace
    - uses: meta4icalbot/pelican-to-github-pages
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}
