name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upgrade pip
      run: pip install --upgrade pip
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: rehanhaider/pelican-to-github-pages@v1.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}
